[project]
name = "baenkliliste-buchhaltung"
version = "0.1.0"
description = "CSV-Schnittstelle zwischen QFieldCloud und der Bänkliverwaltung/Buchhaltung"
requires-python = ">=3.14"
dependencies = [
    "qfieldcloud-sdk==0.17.0",
    "keyring==25.7.0",
    "PySide6==6.11.2",
]
authors = [
    { name = "Urs Mumprecht" }
]

[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]


